apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: rag-api-dr
  namespace: rental-dev
spec:
  host: rag-api.rental-dev.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      http:
        http1MaxPendingRequests: 5
        http2MaxRequests: 5
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
  subsets:
    - name: v1
      labels:
        version: "1.0.0"
