apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  ENVIRONMENT: "qa"
  LOG_LEVEL: "INFO"
  DJANGO_SETTINGS_MODULE: "config.settings.qa"
  RENTAL_SERVICE_URL: "http://rental-service.rental-qa.svc.cluster.local:8001"
  LEDGER_SERVICE_URL: "http://ledger-service.rental-qa.svc.cluster.local:8002"
  NOTIFICATION_SERVICE_URL: "http://notification-service.rental-qa.svc.cluster.local:8003"
  RAG_API_URL: "http://rag-api.rental-qa.svc.cluster.local:8004"
  ALLOWED_HOSTS: "rental-qa.techwizard-platformlab.com"
  CORS_ALLOWED_ORIGINS: "https://rental-qa.techwizard-platformlab.com"
  DEBUG: "false"
  GUNICORN_WORKERS: "4"
  GUNICORN_TIMEOUT: "120"
