apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  ENVIRONMENT: "qa"
  LOG_LEVEL: "INFO"
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  NOTIFICATION_RETRY_COUNT: "3"
  NOTIFICATION_RETRY_DELAY: "10"
