apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-api-config
data:
  ENVIRONMENT: "qa"
  LOG_LEVEL: "INFO"
  LLM_PROVIDER: "groq"
  RATE_LIMIT_PER_MINUTE: "10"
  INDEX_BATCH_SIZE: "100"
  DJANGO_API_URL: "http://api-gateway.rental-qa.svc.cluster.local:80"
