apiVersion: v1
kind: ConfigMap
metadata:
  name: rentalapp-frontend-config
data:
  # QA environment variables
  BACKEND_URL: "http://rental-service.rental-qa.svc.cluster.local:8001"
  NODE_ENV: "production"
