apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # after ESO installs, before ExternalSecrets
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://dev-eus2-kv-4lde.vault.azure.net/"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
