# platform/gitops/argocd/environments/dev/values-gcp.yaml
# GCP-specific overrides for dev environment

environment: dev
cloud: gcp
namespace: rental-dev

repoURL: "https://github.com/techwizard-platformlab/RentalApp-Build"
targetRevision: main

project:
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apps
      kind: Deployment
    - group: networking.istio.io
      kind: VirtualService

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

# Image updater annotations (GCP Artifact Registry)
imageUpdater:
  enabled: true
  image: rental-api
  updateStrategy: semver
  registrySecret: ar-pull-secret

ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
      - /spec/replicas
