apiVersion: v1
kind: Service
metadata:
  name: rag-api
  labels:
    app: rag-api
    project: rentalAppLedger
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  selector:
    app: rag-api
  ports:
    - name: http
      port: 8004
      targetPort: 8004
      protocol: TCP
