apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - servicemonitors/api-gateway-sm.yaml
  - servicemonitors/rental-service-sm.yaml
  - servicemonitors/ledger-service-sm.yaml
  - servicemonitors/notification-service-sm.yaml
  - alerts/api-alerts.yaml
  - alerts/node-alerts.yaml
  - alerts/pod-alerts.yaml
  - dashboards/rentalapp-slo-configmap.yaml
