apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway.yaml
  - peer-auth.yaml
  - destination-rules/api-gateway-dr.yaml
  - destination-rules/rental-service-dr.yaml
  - destination-rules/ledger-service-dr.yaml
  - destination-rules/notification-service-dr.yaml
  - destination-rules/rag-api-dr.yaml
  - destination-rules/frontend-dr.yaml
  - virtual-services/api-gateway-vs.yaml
  - virtual-services/rental-service-vs.yaml
  - virtual-services/ledger-service-vs.yaml
  - virtual-services/rag-api-vs.yaml
  - virtual-services/frontend-vs.yaml
  - authorization-policies/default-deny.yaml
  - authorization-policies/allow-policies.yaml
