apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  ENVIRONMENT: "dev"
  LOG_LEVEL: "DEBUG"
  # Dev: use console email backend so no real emails are sent
  EMAIL_BACKEND: "django.core.mail.backends.console.EmailBackend"
  NOTIFICATION_RETRY_COUNT: "1"
