apiVersion: v1
kind: ConfigMap
metadata:
  name: rentalapp-frontend-config
data:
  # Dev environment variables
  BACKEND_URL: "http://rental-service.rental-dev.svc.cluster.local:8001"
  NODE_ENV: "development"
