apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ledger-service-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: ledger-service-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: django-secret-key
    - secretKey: DB_HOST
      remoteRef:
        key: db-host
    - secretKey: DB_NAME
      remoteRef:
        key: db-name
    - secretKey: DB_USER
      remoteRef:
        key: db-user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-password
    - secretKey: DB_PORT
      remoteRef:
        key: db-port
    - secretKey: DB_ENGINE
      remoteRef:
        key: db-engine
