apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  namespace: rental-dev
  labels:
    app: ledger-service
    project: rentalAppLedger
spec:
  type: ClusterIP
  selector:
    app: ledger-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
