apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: rental-dev
  labels:
    app: api-gateway
    project: rentalAppLedger
data:
  LOG_LEVEL: "INFO"
  DB_HOST: "postgresql.rental-dev.svc.cluster.local"
  ENVIRONMENT: "dev"
  RENTAL_SERVICE_URL: "http://rental-service.rental-dev.svc.cluster.local:8001"
  LEDGER_SERVICE_URL: "http://ledger-service.rental-dev.svc.cluster.local:8002"
