apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: rental-dev
  labels:
    app: notification-service
    project: rentalAppLedger
data:
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "dev"
