apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    project: rentalAppLedger
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
