apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rental-service-sm
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: rental-service
    project: rentalAppLedger
spec:
  selector:
    matchLabels:
      app: rental-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - rental-dev
      - rental-qa
