apiVersion: v1
kind: ConfigMap
metadata:
  name: rental-service-config
  labels:
    app: rental-service
    project: rentalAppLedger
data:
  LOG_LEVEL: "INFO"
  DJANGO_SETTINGS_MODULE: "config.settings.base"
  SERVICE_PORT: "8001"
  GUNICORN_WORKERS: "2"
  GUNICORN_TIMEOUT: "60"
