apiVersion: v1
kind: Service
metadata:
  name: rental-service
  namespace: rental-dev
  labels:
    app: rental-service
    project: rentalAppLedger
spec:
  type: ClusterIP
  selector:
    app: rental-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
