apiVersion: v1
kind: Service
metadata:
  name: rental-service
  labels:
    app: rental-service
    project: rentalAppLedger
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  selector:
    app: rental-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
