apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rental-qa

resources:
  - ../../base/api-gateway
  - ../../base/rental-service
  - ../../base/ledger-service
  - ../../base/notification-service

commonLabels:
  environment: qa

# QA: patch replicas to 2 and HPA min to 2 for all services
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      labelSelector: "project=rentalAppLedger"

  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
    target:
      kind: HorizontalPodAutoscaler
      labelSelector: "project=rentalAppLedger"

  # Point configmaps to qa namespace environment value
  - patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: qa
    target:
      kind: ConfigMap
      labelSelector: "project=rentalAppLedger"
